# Generated by Django 3.0.6 on 2020-05-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid19',
            name='Active',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='covid19',
            name='Confirmed',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='covid19',
            name='Deaths',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='covid19',
            name='Recovered',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='covid19',
            name='State',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
