# Generated by Django 3.0.6 on 2020-05-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0002_auto_20200527_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid19',
            name='Active',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='covid19',
            name='Confirmed',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='covid19',
            name='Deaths',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='covid19',
            name='Recovered',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='covid19',
            name='State',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
